export interface SurahMetadata {
  id: number;
  englishName: string;
  arabicName: string;
}

export const SURAH_METADATA: SurahMetadata[] = [
  { id: 1, englishName: "Al-Fatihah (The Opener)", arabicName: "الفاتحة" },
  { id: 2, englishName: "Al-Baqarah (The Cow)", arabicName: "البقرة" },
  { id: 3, englishName: "Ali 'Imran (Family of Imran)", arabicName: "آل عمران" },
  { id: 4, englishName: "An-Nisa (The Women)", arabicName: "النساء" },
  { id: 5, englishName: "Al-Ma'idah (The Table Spread)", arabicName: "المائدة" },
  { id: 6, englishName: "Al-An'am (The Cattle)", arabicName: "الأنعام" },
  { id: 7, englishName: "Al-A'raf (The Heights)", arabicName: "الأعراف" },
  { id: 8, englishName: "Al-Anfal (The Spoils of War)", arabicName: "الأنفال" },
  { id: 9, englishName: "At-Tawbah (The Repentance)", arabicName: "التوبة" },
  { id: 10, englishName: "Yunus (Jonah)", arabicName: "يونس" },
  { id: 11, englishName: "Hud (Hud)", arabicName: "هود" },
  { id: 12, englishName: "Yusuf (Joseph)", arabicName: "يوسف" },
  { id: 13, englishName: "Ar-Ra'd (The Thunder)", arabicName: "الرعد" },
  { id: 14, englishName: "Ibrahim (Abraham)", arabicName: "إبراهيم" },
  { id: 15, englishName: "Al-Hijr (The Rocky Tract)", arabicName: "الحجر" },
  { id: 16, englishName: "An-Nahl (The Bee)", arabicName: "النحل" },
  { id: 17, englishName: "Al-Isra (The Night Journey)", arabicName: "الإسراء" },
  { id: 18, englishName: "Al-Kahf (The Cave)", arabicName: "الكهف" },
  { id: 19, englishName: "Maryam (Mary)", arabicName: "مريم" },
  { id: 20, englishName: "Ta-Ha (Ta-Ha)", arabicName: "طه" },
  { id: 21, englishName: "Al-Anbya (The Prophets)", arabicName: "الأنبياء" },
  { id: 22, englishName: "Al-Hajj (The Pilgrimage)", arabicName: "الحج" },
  { id: 23, englishName: "Al-Mu'minun (The Believers)", arabicName: "المؤمنون" },
  { id: 24, englishName: "An-Nur (The Light)", arabicName: "النور" },
  { id: 25, englishName: "Al-Furqan (The Criterion)", arabicName: "الفرقان" },
  { id: 26, englishName: "Ash-Shu'ara (The Poets)", arabicName: "الشعراء" },
  { id: 27, englishName: "An-Naml (The Ant)", arabicName: "النمل" },
  { id: 28, englishName: "Al-Qasas (The Stories)", arabicName: "القصص" },
  { id: 29, englishName: "Al-'Ankabut (The Spider)", arabicName: "العنكبوت" },
  { id: 30, englishName: "Ar-Rum (The Romans)", arabicName: "الروم" },
  { id: 31, englishName: "Luqman (Luqman)", arabicName: "لقمان" },
  { id: 32, englishName: "As-Sajdah (The Prostration)", arabicName: "السجدة" },
  { id: 33, englishName: "Al-Ahzab (The Combined Forces)", arabicName: "الأحزاب" },
  { id: 34, englishName: "Saba (Sheba)", arabicName: "سبأ" },
  { id: 35, englishName: "Fatir (The Originator)", arabicName: "فاطر" },
  { id: 36, englishName: "Ya-Sin (Ya-Sin)", arabicName: "يس" },
  { id: 37, englishName: "As-Saffat (Those Who Set the Ranks)", arabicName: "الصافات" },
  { id: 38, englishName: "Sad (Sad)", arabicName: "ص" },
  { id: 39, englishName: "Az-Zumar (The Troops)", arabicName: "الزمر" },
  { id: 40, englishName: "Ghafir (The Forgiver)", arabicName: "غافر" },
  { id: 41, englishName: "Fussilat (Explained in Detail)", arabicName: "فصلت" },
  { id: 42, englishName: "Ash-Shura (The Consultation)", arabicName: "الشورى" },
  { id: 43, englishName: "Az-Zukhruf (The Ornaments of Gold)", arabicName: "الزخرف" },
  { id: 44, englishName: "Ad-Dukhan (The Smoke)", arabicName: "الدخان" },
  { id: 45, englishName: "Al-Jathiyah (The Crouching)", arabicName: "الجاثية" },
  { id: 46, englishName: "Al-Ahqaf (The Wind-Curved Sandhills)", arabicName: "الأحقاف" },
  { id: 47, englishName: "Muhammad (Muhammad)", arabicName: "محمد" },
  { id: 48, englishName: "Al-Fath (The Victory)", arabicName: "الفتح" },
  { id: 49, englishName: "Al-Hujurat (The Rooms)", arabicName: "الحجرات" },
  { id: 50, englishName: "Qaf (Qaf)", arabicName: "ق" },
  { id: 51, englishName: "Adh-Dhariyat (The Winnowing Winds)", arabicName: "الذاريات" },
  { id: 52, englishName: "At-Tur (The Mount)", arabicName: "الطور" },
  { id: 53, englishName: "An-Najm (The Star)", arabicName: "النجم" },
  { id: 54, englishName: "Al-Qamar (The Moon)", arabicName: "القمر" },
  { id: 55, englishName: "Ar-Rahman (The Beneficent)", arabicName: "الرحمن" },
  { id: 56, englishName: "Al-Waqi'ah (The Inevitable)", arabicName: "الواقعة" },
  { id: 57, englishName: "Al-Hadid (The Iron)", arabicName: "الحديد" },
  { id: 58, englishName: "Al-Mujadila (The Pleading Woman)", arabicName: "المجادلة" },
  { id: 59, englishName: "Al-Hashr (The Exile)", arabicName: "الحشر" },
  { id: 60, englishName: "Al-Mumtahanah (She That Is To Be Examined)", arabicName: "الممتحنة" },
  { id: 61, englishName: "As-Saff (The Ranks)", arabicName: "الصف" },
  { id: 62, englishName: "Al-Jumu'ah (The Congregation)", arabicName: "الجمعة" },
  { id: 63, englishName: "Al-Munafiqun (The Hypocrites)", arabicName: "المنافقون" },
  { id: 64, englishName: "At-Taghabun (The Mutual Disillusion)", arabicName: "التغابن" },
  { id: 65, englishName: "At-Talaq (The Divorce)", arabicName: "الطلاق" },
  { id: 66, englishName: "At-Tahrim (The Prohibition)", arabicName: "التحريم" },
  { id: 67, englishName: "Al-Mulk (The Sovereignty)", arabicName: "الملك" },
  { id: 68, englishName: "Al-Qalam (The Pen)", arabicName: "القلم" },
  { id: 69, englishName: "Al-Haqqah (The Inevitable)", arabicName: "الحاقة" },
  { id: 70, englishName: "Al-Ma'arij (The Ascending Stairways)", arabicName: "المعارج" },
  { id: 71, englishName: "Nuh (Noah)", arabicName: "نوح" },
  { id: 72, englishName: "Al-Jinn (The Jinn)", arabicName: "الجن" },
  { id: 73, englishName: "Al-Muzzammil (The Enshrouded One)", arabicName: "المزمل" },
  { id: 74, englishName: "Al-Muddathir (The Cloaked One)", arabicName: "المدثر" },
  { id: 75, englishName: "Al-Qiyamah (The Resurrection)", arabicName: "القيامة" },
  { id: 76, englishName: "Al-Insan (The Man)", arabicName: "الإنسان" },
  { id: 77, englishName: "Al-Mursalat (The Emissaries)", arabicName: "المرسلات" },
  { id: 78, englishName: "An-Naba (The Tidings)", arabicName: "النبأ" },
  { id: 79, englishName: "An-Nazi'at (Those Who Drag Forth)", arabicName: "النازعات" },
  { id: 80, englishName: "'Abasa (He Frowned)", arabicName: "عبس" },
  { id: 81, englishName: "At-Takwir (The Overthrowing)", arabicName: "التكوير" },
  { id: 82, englishName: "Al-Infitar (The Cleaving)", arabicName: "الانفطار" },
  { id: 83, englishName: "Al-Mutaffifin (The Defrauding)", arabicName: "المطففين" },
  { id: 84, englishName: "Al-Inshiqaq (The Splitting Open)", arabicName: "الانشقاق" },
  { id: 85, englishName: "Al-Buruj (The Constellations)", arabicName: "البروج" },
  { id: 86, englishName: "At-Tariq (The Morning Star)", arabicName: "الطارق" },
  { id: 87, englishName: "Al-A'la (The Most High)", arabicName: "الأعلى" },
  { id: 88, englishName: "Al-Ghashiyah (The Overwhelming)", arabicName: "الغاشية" },
  { id: 89, englishName: "Al-Fajr (The Dawn)", arabicName: "الفجر" },
  { id: 90, englishName: "Al-Balad (The City)", arabicName: "البلد" },
  { id: 91, englishName: "Ash-Shams (The Sun)", arabicName: "الشمس" },
  { id: 92, englishName: "Al-Layl (The Night)", arabicName: "الليل" },
  { id: 93, englishName: "Ad-Duha (The Morning Brightness)", arabicName: "الضحى" },
  { id: 94, englishName: "Ash-Sharh (The Relief)", arabicName: "الشرح" },
  { id: 95, englishName: "At-Tin (The Fig)", arabicName: "التين" },
  { id: 96, englishName: "Al-'Alaq (The Clot)", arabicName: "العلق" },
  { id: 97, englishName: "Al-Qadr (The Power)", arabicName: "القدر" },
  { id: 98, englishName: "Al-Bayyinah (The Clear Proof)", arabicName: "البينة" },
  { id: 99, englishName: "Az-Zalzalah (The Earthquake)", arabicName: "الزلزلة" },
  { id: 100, englishName: "Al-'Adiyat (The Courser)", arabicName: "العاديات" },
  { id: 101, englishName: "Al-Qari'ah (The Calamity)", arabicName: "القارعة" },
  { id: 102, englishName: "At-Takathur (The Rivalry in Worldly Increase)", arabicName: "التكاثر" },
  { id: 103, englishName: "Al-'Asr (The Declining Day)", arabicName: "العصر" },
  { id: 104, englishName: "Al-Humazah (The Slanderer)", arabicName: "الهمزة" },
  { id: 105, englishName: "Al-Fil (The Elephant)", arabicName: "الفيل" },
  { id: 106, englishName: "Quraysh (Quraysh)", arabicName: "قريش" },
  { id: 107, englishName: "Al-Ma'un (The Small Kindnesses)", arabicName: "الماعون" },
  { id: 108, englishName: "Al-Kawthar (The Abundance)", arabicName: "الكوثر" },
  { id: 109, englishName: "Al-Kafirun (The Disbelievers)", arabicName: "الكافرون" },
  { id: 110, englishName: "An-Nasr (The Divine Support)", arabicName: "النصر" },
  { id: 111, englishName: "Al-Masad (The Palm Fiber)", arabicName: "المسد" },
  { id: 112, englishName: "Al-Ikhlas (The Sincerity)", arabicName: "الإخلاص" },
  { id: 113, englishName: "Al-Falaq (The Daybreak)", arabicName: "الفلق" },
  { id: 114, englishName: "An-Nas (The Mankind)", arabicName: "الناس" },
];

