export type SurahMetadata = {
  number: number;
  englishName: string;
  arabicName: string;
  transliteration: string;
};

export const surahMetadata = [
  {
    number: 1,
    englishName: "The Opening",
    arabicName: "الفاتحة",
    transliteration: "Al-Fatiha",
  },
  {
    number: 2,
    englishName: "The Cow",
    arabicName: "البقرة",
    transliteration: "Al-Baqarah",
  },
  {
    number: 3,
    englishName: "The Family of Imran",
    arabicName: "آل عمران",
    transliteration: "Aal-E-Imran",
  },
  {
    number: 4,
    englishName: "The Women",
    arabicName: "النساء",
    transliteration: "An-Nisa",
  },
  {
    number: 5,
    englishName: "The Table Spread",
    arabicName: "المائدة",
    transliteration: "Al-Ma'idah",
  },
  {
    number: 6,
    englishName: "The Cattle",
    arabicName: "الأنعام",
    transliteration: "Al-An'am",
  },
  {
    number: 7,
    englishName: "The Heights",
    arabicName: "الأعراف",
    transliteration: "Al-A'raf",
  },
  {
    number: 8,
    englishName: "The Spoils of War",
    arabicName: "الأنفال",
    transliteration: "Al-Anfal",
  },
  {
    number: 9,
    englishName: "The Repentance",
    arabicName: "التوبة",
    transliteration: "At-Tawbah",
  },
  { number: 10, englishName: "Jonah", arabicName: "يونس", transliteration: "Yunus" },
  { number: 11, englishName: "Hud", arabicName: "هود", transliteration: "Hud" },
  { number: 12, englishName: "Joseph", arabicName: "يوسف", transliteration: "Yusuf" },
  { number: 13, englishName: "Thunder", arabicName: "الرعد", transliteration: "Ar-Ra'd" },
  { number: 14, englishName: "Abraham", arabicName: "إبراهيم", transliteration: "Ibrahim" },
  { number: 15, englishName: "The Rocky Tract", arabicName: "الحجر", transliteration: "Al-Hijr" },
  { number: 16, englishName: "The Bee", arabicName: "النحل", transliteration: "An-Nahl" },
  { number: 17, englishName: "The Night Journey", arabicName: "الإسراء", transliteration: "Al-Isra" },
  { number: 18, englishName: "The Cave", arabicName: "الكهف", transliteration: "Al-Kahf" },
  { number: 19, englishName: "Mary", arabicName: "مريم", transliteration: "Maryam" },
  { number: 20, englishName: "Ta-Ha", arabicName: "طه", transliteration: "Ta-Ha" },
  { number: 21, englishName: "The Prophets", arabicName: "الأنبياء", transliteration: "Al-Anbiya" },
  { number: 22, englishName: "The Pilgrimage", arabicName: "الحج", transliteration: "Al-Hajj" },
  { number: 23, englishName: "The Believers", arabicName: "المؤمنون", transliteration: "Al-Mu'minun" },
  { number: 24, englishName: "The Light", arabicName: "النور", transliteration: "An-Nur" },
  { number: 25, englishName: "The Criterion", arabicName: "الفرقان", transliteration: "Al-Furqan" },
  { number: 26, englishName: "The Poets", arabicName: "الشعراء", transliteration: "Ash-Shu'ara" },
  { number: 27, englishName: "The Ant", arabicName: "النمل", transliteration: "An-Naml" },
  { number: 28, englishName: "The Stories", arabicName: "القصص", transliteration: "Al-Qasas" },
  { number: 29, englishName: "The Spider", arabicName: "العنكبوت", transliteration: "Al-Ankabut" },
  { number: 30, englishName: "The Romans", arabicName: "الروم", transliteration: "Ar-Rum" },
  { number: 31, englishName: "Luqman", arabicName: "لقمان", transliteration: "Luqman" },
  { number: 32, englishName: "The Prostration", arabicName: "السجدة", transliteration: "As-Sajdah" },
  { number: 33, englishName: "The Combined Forces", arabicName: "الأحزاب", transliteration: "Al-Ahzab" },
  { number: 34, englishName: "Sheba", arabicName: "سبأ", transliteration: "Saba" },
  { number: 35, englishName: "The Originator", arabicName: "فاطر", transliteration: "Fatir" },
  { number: 36, englishName: "Ya-Sin", arabicName: "يس", transliteration: "Ya-Sin" },
  { number: 37, englishName: "Those Who Set the Ranks", arabicName: "الصافات", transliteration: "As-Saffat" },
  { number: 38, englishName: "Sad", arabicName: "ص", transliteration: "Sad" },
  { number: 39, englishName: "The Troops", arabicName: "الزمر", transliteration: "Az-Zumar" },
  { number: 40, englishName: "The Forgiver", arabicName: "غافر", transliteration: "Ghafir" },
  { number: 41, englishName: "Explained in Detail", arabicName: "فصلت", transliteration: "Fussilat" },
  { number: 42, englishName: "The Consultation", arabicName: "الشورى", transliteration: "Ash-Shura" },
  { number: 43, englishName: "The Gold Adornments", arabicName: "الزخرف", transliteration: "Az-Zukhruf" },
  { number: 44, englishName: "The Smoke", arabicName: "الدخان", transliteration: "Ad-Dukhan" },
  { number: 45, englishName: "The Crouching", arabicName: "الجاثية", transliteration: "Al-Jathiyah" },
  {
    number: 46,
    englishName: "The Wind-Curved Sandhills",
    arabicName: "الأحقاف",
    transliteration: "Al-Ahqaf",
  },
  { number: 47, englishName: "Muhammad", arabicName: "محمد", transliteration: "Muhammad" },
  { number: 48, englishName: "The Victory", arabicName: "الفتح", transliteration: "Al-Fath" },
  { number: 49, englishName: "The Rooms", arabicName: "الحجرات", transliteration: "Al-Hujurat" },
  { number: 50, englishName: "Qaf", arabicName: "ق", transliteration: "Qaf" },
  { number: 51, englishName: "The Winnowing Winds", arabicName: "الذاريات", transliteration: "Adh-Dhariyat" },
  { number: 52, englishName: "The Mount", arabicName: "الطور", transliteration: "At-Tur" },
  { number: 53, englishName: "The Star", arabicName: "النجم", transliteration: "An-Najm" },
  { number: 54, englishName: "The Moon", arabicName: "القمر", transliteration: "Al-Qamar" },
  { number: 55, englishName: "The Most Merciful", arabicName: "الرحمن", transliteration: "Ar-Rahman" },
  { number: 56, englishName: "The Inevitable", arabicName: "الواقعة", transliteration: "Al-Waqi'ah" },
  { number: 57, englishName: "The Iron", arabicName: "الحديد", transliteration: "Al-Hadid" },
  { number: 58, englishName: "The Pleading Woman", arabicName: "المجادلة", transliteration: "Al-Mujadilah" },
  { number: 59, englishName: "The Exile", arabicName: "الحشر", transliteration: "Al-Hashr" },
  {
    number: 60,
    englishName: "She That Is to Be Examined",
    arabicName: "الممتحنة",
    transliteration: "Al-Mumtahanah",
  },
  { number: 61, englishName: "The Ranks", arabicName: "الصف", transliteration: "As-Saff" },
  { number: 62, englishName: "The Congregation", arabicName: "الجمعة", transliteration: "Al-Jumu'ah" },
  { number: 63, englishName: "The Hypocrites", arabicName: "المنافقون", transliteration: "Al-Munafiqun" },
  {
    number: 64,
    englishName: "The Mutual Disillusion",
    arabicName: "التغابن",
    transliteration: "At-Taghabun",
  },
  { number: 65, englishName: "Divorce", arabicName: "الطلاق", transliteration: "At-Talaq" },
  { number: 66, englishName: "The Prohibition", arabicName: "التحريم", transliteration: "At-Tahrim" },
  { number: 67, englishName: "The Sovereignty", arabicName: "الملك", transliteration: "Al-Mulk" },
  { number: 68, englishName: "The Pen", arabicName: "القلم", transliteration: "Al-Qalam" },
  { number: 69, englishName: "The Reality", arabicName: "الحاقة", transliteration: "Al-Haqqah" },
  {
    number: 70,
    englishName: "The Ascending Stairways",
    arabicName: "المعارج",
    transliteration: "Al-Ma'arij",
  },
  { number: 71, englishName: "Noah", arabicName: "نوح", transliteration: "Nuh" },
  { number: 72, englishName: "The Jinn", arabicName: "الجن", transliteration: "Al-Jinn" },
  { number: 73, englishName: "The Enshrouded One", arabicName: "المزمل", transliteration: "Al-Muzzammil" },
  { number: 74, englishName: "The Cloaked One", arabicName: "المدثر", transliteration: "Al-Muddaththir" },
  { number: 75, englishName: "The Resurrection", arabicName: "القيامة", transliteration: "Al-Qiyamah" },
  { number: 76, englishName: "The Human", arabicName: "الإنسان", transliteration: "Al-Insan" },
  { number: 77, englishName: "The Emissaries", arabicName: "المرسلات", transliteration: "Al-Mursalat" },
  { number: 78, englishName: "The Tidings", arabicName: "النبأ", transliteration: "An-Naba" },
  { number: 79, englishName: "Those Who Drag Forth", arabicName: "النازعات", transliteration: "An-Nazi'at" },
  { number: 80, englishName: "He Frowned", arabicName: "عبس", transliteration: "Abasa" },
  { number: 81, englishName: "The Overthrowing", arabicName: "التكوير", transliteration: "At-Takwir" },
  { number: 82, englishName: "The Cleaving", arabicName: "الانفطار", transliteration: "Al-Infitar" },
  { number: 83, englishName: "Defrauding", arabicName: "المطففين", transliteration: "Al-Mutaffifin" },
  { number: 84, englishName: "The Splitting Open", arabicName: "الانشقاق", transliteration: "Al-Inshiqaq" },
  { number: 85, englishName: "The Mansions of the Stars", arabicName: "البروج", transliteration: "Al-Buruj" },
  { number: 86, englishName: "The Nightcomer", arabicName: "الطارق", transliteration: "At-Tariq" },
  { number: 87, englishName: "The Most High", arabicName: "الأعلى", transliteration: "Al-A'la" },
  {
    number: 88,
    englishName: "The Overwhelming Event",
    arabicName: "الغاشية",
    transliteration: "Al-Ghashiyah",
  },
  { number: 89, englishName: "The Dawn", arabicName: "الفجر", transliteration: "Al-Fajr" },
  { number: 90, englishName: "The City", arabicName: "البلد", transliteration: "Al-Balad" },
  { number: 91, englishName: "The Sun", arabicName: "الشمس", transliteration: "Ash-Shams" },
  { number: 92, englishName: "The Night", arabicName: "الليل", transliteration: "Al-Layl" },
  { number: 93, englishName: "The Morning Hours", arabicName: "الضحى", transliteration: "Ad-Duha" },
  { number: 94, englishName: "The Relief", arabicName: "الشرح", transliteration: "Ash-Sharh" },
  { number: 95, englishName: "The Fig", arabicName: "التين", transliteration: "At-Tin" },
  { number: 96, englishName: "The Clot", arabicName: "العلق", transliteration: "Al-'Alaq" },
  { number: 97, englishName: "The Power", arabicName: "القدر", transliteration: "Al-Qadr" },
  { number: 98, englishName: "The Clear Proof", arabicName: "البينة", transliteration: "Al-Bayyinah" },
  { number: 99, englishName: "The Earthquake", arabicName: "الزلزلة", transliteration: "Az-Zalzalah" },
  { number: 100, englishName: "The Courser", arabicName: "العاديات", transliteration: "Al-'Adiyat" },
  { number: 101, englishName: "The Striking Hour", arabicName: "القارعة", transliteration: "Al-Qari'ah" },
  { number: 102, englishName: "Competition", arabicName: "التكاثر", transliteration: "At-Takathur" },
  { number: 103, englishName: "The Declining Day", arabicName: "العصر", transliteration: "Al-'Asr" },
  { number: 104, englishName: "The Traducer", arabicName: "الهمزة", transliteration: "Al-Humazah" },
  { number: 105, englishName: "The Elephant", arabicName: "الفيل", transliteration: "Al-Fil" },
  { number: 106, englishName: "Quraysh", arabicName: "قريش", transliteration: "Quraysh" },
  { number: 107, englishName: "Small Kindnesses", arabicName: "الماعون", transliteration: "Al-Ma'un" },
  { number: 108, englishName: "Abundance", arabicName: "الكوثر", transliteration: "Al-Kawthar" },
  { number: 109, englishName: "The Disbelievers", arabicName: "الكافرون", transliteration: "Al-Kafirun" },
  { number: 110, englishName: "Divine Support", arabicName: "النصر", transliteration: "An-Nasr" },
  { number: 111, englishName: "The Palm Fiber", arabicName: "المسد", transliteration: "Al-Masad" },
  { number: 112, englishName: "Sincerity", arabicName: "الإخلاص", transliteration: "Al-Ikhlas" },
  { number: 113, englishName: "The Daybreak", arabicName: "الفلق", transliteration: "Al-Falaq" },
  { number: 114, englishName: "Mankind", arabicName: "الناس", transliteration: "An-Nas" },
] as const satisfies ReadonlyArray<SurahMetadata>;

export const surahMetadataById = surahMetadata.map((item) => ({
  ...item,
  id: item.number,
}));

export const getSurahMetadata = (surahNumber: number) =>
  surahMetadataById.find((item) => item.id === surahNumber);

export type SurahMetadataItem = (typeof surahMetadata)[number];
